main:
  backend: ncurses
  keymap: default

macos:
  allow_kbd_hook: yes

ncurses:

editor:

#
# Add ability to include user-name, and other things here (working dir???)
#
commandmode:
  prompt: "ed>"


terminal:
  shell: /bin/zsh
  init: -is
  bootstrap:
    - SET XYZ=4
    - export path=%path%
    - ls -laF

theme:
  sublime_colorfile: "tests/colors.sublime.json"

languages:
  default:
    indent: 4
    tabsize: 4
    insert_spaces: yes
  cpp:
    insert_closing_brace: yes
    auto_indent: yes
    continue_comment: yes


