main:
  backend: ncurses
  # select the keymap default for the backend
  # 'default' is a reserved word - replace with your file name when forking it...
  keymap: default

macos:
  allow_kbd_hook: yes

sdl3:
  default_width: 1024
  default_height: 768
  # When drawing underlined text this defines how many pixels from the regular baseline of the font to offset the line
  text_underline_margin: 16
  # this increases the spacing between lines - it is added to the baseline of the font
  line_margin: 4
  keymap: "sdl3_default.keymap"

ncurses:
  timeoutKeyEvent: 500
  keymap: "ncurses_default.keymap"

editor:
  # content_first is CLion/Sublime style (no = VSCode style, cursor first)
  pgupdown_content_first: yes

#
# Add ability to include user-name, and other things here (working dir???)
#
commandmode:
  prompt: "ed>"
  cmdlet_prefix: "."


keymap: {
    # Editor will read this and check the modifier mask controlling an action
    # For instance, the 'SelectionModifier' is used to enable/disable selections
    modifiers: {
      SelectionModifier: KeyCode_Shift,
      CopyPasteModifier: KeyCode_Cmd,
    },
    actions: {
      NavigateLineUp : KeyCode_UpArrow + @SelectionModifier,
      NavigateLineDown : KeyCode_DownArrow + @SelectionModifier,
      NavigateLeft : KeyCode_LeftArrow + @SelectionModifier,
      NavigateRight : KeyCode_RightArrow + @SelectionModifier,
      NavigatePageUp : KeyCode_PageUp + @SelectionModifier,
      NavigatePageDown : KeyCode_PageDown + @SelectionModifier,
      CopyToClipboard : CopyPasteModifier + 'c',
      PasteFromClipboard : CopyPasteModifier + 'v',
      CycleActiveView : KeyCode_Escape,
      CycleActiveEditor : KeyCode_F3,
      CommitLine : KeyCode_Return,
    }
}

# old keymap
# This keymap is tested with macbook with external keyboard..
# Note: Keymap should point to a file instead..
temptemp: {
  # test
  #KeyCode_Shift + KeyCode_UpArrow : NavigateEnd,
  #KeyCode_Ctrl + KeyCode_Shift + KeyCode_UpArrow : NavigateHome,
  # properly mapped
  KeyCode_UpArrow : NavigateLineUp,
  KeyCode_DownArrow : NavigateLineDown,

  # Test - map to same action - but NavigateLineDown will check if this is pressed and invoke selection..
  KeyCode_Shift + KeyCode_DownArrow : NavigateLineDown,
  KeyCode_Shift + KeyCode_UpArrow : NavigateLineUp,

  # Should be able to mark a modifier as 'optional' for an action
  # like: KeyCode_DownArray + @KeyCode_Shift : NavigateDown
  # or:   @KeyCode_Shift + KeyCode_DownArray : NavigateDown
  #
  # This would then insert two actions in the table one with 'Shift' and one without..
  # Or Perhaps lik this:
  #
  # @SelectionModifier + KeyCode_DownArray : NavigateDown
  #
  # Change this to:
  # Action = Key combo
  # Will allow for other stuff like: var <variable> : some key code stuff
  # and then reuse/substitue later will be easier and more 'logical'
  # It also reads like a proper expression...
  #

  KeyCode_LeftArrow : NavigateLineStepLeft,
  KeyCode_RightArrow : NavigateLineStepRight,
  KeyCode_PageUp : NavigatePageUp,
  KeyCode_PageDown : NavigatePageDown,
  KeyCode_Return : CommitLine,
  KeyCode_Command + KeyCode_Home : GotoFirstLine,
  KeyCode_Command + KeyCode_End : GotoLastLine,
  KeyCode_Command + KeyCode_PageUp : GotoTopLine,
  KeyCode_Command + KeyCode_PageDown : GotoBottomLine,
  # doesnt work on MacBookPro laptop keyboard (ALT+Left/RightArrow return 'b'/'f' - modifier is correct!)
  KeyCode_LeftCmd + KeyCode_LeftArrow : NavigateLineWordLeft,
  KeyCode_LeftCmd + KeyCode_RightArrow : NavigateLineWordRight,
  KeyCode_Escape : CycleActiveView,
  KeyCode_F3 : CycleActiveEditor,

  KeyCode_Command + 'c' : CopyToClipboard,
  KeyCode_Command + 'v' : PasteFromClipboard,

}

# we

terminal:
  shell: /bin/zsh
  init: -is
  bootstrap:
    - SET XYZ=4
    - export path=%path%
    - ls -laF

theme:
  sublime_colorfile: "colors.sublime.json"

languages:
  default:
    indent: 4
    tabsize: 4
    insert_spaces: yes
  cpp:
    insert_closing_brace: yes
    auto_indent: yes
    continue_comment: yes
