main:
  backend: ncurses
  # select the keymap default for the backend
  # 'default' is a reserved word - replace with your file name when forking it...
  keymap: default

macos:
  allow_kbd_hook: yes

sdl3:
  default_width: 1920
  default_height: 1080
  keymap: "sdl3_default.keymap"

ncurses:
  timeoutKeyEvent: 500
  keymap: "ncurses_default.keymap"

editor:
  # content_first is CLion/Sublime style (no = VSCode style, cursor first)
  pgupdown_content_first: yes

#
# Add ability to include user-name, and other things here (working dir???)
#
commandmode:
  prompt: "ed>"
  cmdlet_prefix: "."

# This keymap is tested with macbook with external keyboard..
# Note: Keymap should point to a file instead..
defaultkeymap: {
  # test
  KeyCode_Shift + KeyCode_UpArrow : NavigateEnd,
  KeyCode_Ctrl + KeyCode_Shift + KeyCode_UpArrow : NavigateHome,
  # properly mapped
  KeyCode_UpArrow : NavigateLineUp,
  KeyCode_DownArrow : NavigateLineDown,
  KeyCode_LeftArrow : NavigateLineStepLeft,
  KeyCode_RightArrow : NavigateLineStepRight,
  KeyCode_PageUp : NavigatePageUp,
  KeyCode_PageDown : NavigatePageDown,
  KeyCode_Return : CommitLine,
  KeyCode_Command + KeyCode_Home : GotoFirstLine,
  KeyCode_Command + KeyCode_End : GotoLastLine,
  KeyCode_Command + KeyCode_PageUp : GotoTopLine,
  KeyCode_Command + KeyCode_PageDown : GotoBottomLine,
  # doesnt work on MacBookPro laptop keyboard (ALT+Left/RightArrow return 'b'/'f' - modifier is correct!)
  KeyCode_LeftCmd + KeyCode_LeftArrow : NavigateLineWordLeft,
  KeyCode_LeftCmd + KeyCode_RightArrow : NavigateLineWordRight,
  KeyCode_Escape : CycleActiveView,
  KeyCode_F3 : CycleActiveEditor,
}

# we

terminal:
  shell: /bin/zsh
  init: -is
  bootstrap:
    - SET XYZ=4
    - export path=%path%
    - ls -laF

theme:
  sublime_colorfile: "colors.sublime.json"

languages:
  default:
    indent: 4
    tabsize: 4
    insert_spaces: yes
  cpp:
    insert_closing_brace: yes
    auto_indent: yes
    continue_comment: yes
