main:
  backend: ncurses
  keymap: default

macos:
  allow_kbd_hook: yes

ncurses:
  timeoutKeyEvent: 500

editor:
  # content_first is CLion/Sublime style (no = VSCode style, cursor first)
  pgupdown_content_first: yes

#
# Add ability to include user-name, and other things here (working dir???)
#
commandmode:
  prompt: "ed>"
  cmdlet_prefix: '.'

defaultkeymap: {
  # test
  KeyCode_Shift + KeyCode_UpArrow : NavigateEnd,
  KeyCode_Ctrl + KeyCode_Shift + KeyCode_UpArrow : NavigateHome,
  # properly mapped
  KeyCode_UpArrow : NavigateLineUp,
  KeyCode_DownArrow : NavigateLineDown,
  KeyCode_LeftArrow : NavigateLineStepLeft,
  KeyCode_RightArrow : NavigateLineStepRight,
  KeyCode_Return : CommitLine,
  KeyCode_Command + KeyCode_Home : GotoFirstList,
  KeyCode_Command + KeyCode_End : GotoLastList,
  KeyCode_Command + KeyCode_PageUp : NavigateToTopLine,
  KeyCode_Command + KeyCode_PageDown : NavigateToBottomLine,
}


terminal:
  shell: /bin/zsh
  init: -is
  bootstrap:
    - SET XYZ=4
    - export path=%path%
    - ls -laF

theme:
  sublime_colorfile: "tests/colors.sublime.json"

languages:
  default:
    indent: 4
    tabsize: 4
    insert_spaces: yes
  cpp:
    insert_closing_brace: yes
    auto_indent: yes
    continue_comment: yes


