main:
  backend: sdl
  theme: default.theme.yml
  # select the keymap default for the backend
  # 'default' is a reserved word - replace with your file name when forking it...
  keymap: "default_keymap"
  threaded_syntaxparser: yes
  plugin_directory: Plugins
  bootstrap_script_comment: "//"
  cmdlet_prefix: "."
  bootstrap_scripts:
    - bootstrap.script
    - ~/.gedit

#
# During initial boot up the console is the logger but once we have the config loaded the logger will reinitalize
#
logging:
  # supported options: filesink, console
  logsink: filesink
  logfile: goatedit.log
  disable_all: no
  enable_modules:
    - "System"
    - "VNavModel"
    - "EditorView"


foldermonitor:
  enabled: yes
  use_git_ignore: yes
  # Note: for macos this can only be maximum 8 folders - or else!
  exclude:
    - ".git"
    - ".idea"
    - "bld"
    - "cmake-build-debug"
    - "cmake-build-release"

#
# keymapping varies a bit for native feel, thus - each OS has their own file to map nicely
# in order to change this you need to copy the file and override it completely
# note: DO NOT use the same filename as in the default configuration!
#
macos:
  allow_kbd_hook: no
  default_keymap: macOS/default_keymap.yml
  quickmode_keymap: macOS/quickmode_keymap.yml
  workspace_keymap: macOS/workspace_keymap.yml

linux:
  default_keymap: Linux/default_keymap.yml
  quickmode_keymap: Linux/quickmode_keymap.yml
  workspace_keymap: Linux/workspace_keymap.yml

sdl:
  default_width: 1024
  default_height: 768
  # Defines the SDL window rendering backend 'opengl', 'vulkan', 'metal' - empty or unknown means default...
  backend: "opengl"
  # When drawing underlined text this defines how many pixels from the regular baseline of the font to offset the line
  text_underline_margin: 16
  # this increases the spacing between lines - it is added to the baseline of the font
  line_margin: 4

ncurses:
  timeoutKeyEvent: 500
  keymap: "ncurses_default.keymap"

#
# Set up details for the 3 main views
#

editorview:
  # content_first is CLion/Sublime style (no = VSCode style, cursor first)
  pgupdown_content_first: yes
  keymap: "default_keymap"

workspaceview:
  keymap: "workspace_keymap"
  switch_to_editor_on_openfile: yes

#
# Add ability to include user-name, and other things here (working dir???)
#
commandview:
  prompt: "ed>"


quickmode:
  # this will leave the quick-command mode automatically when a successfull command has been executed
  # while this can be nice, it's cumbersome if used for navigation...
  leave_automatically: true
  leave_when_switching_view: true
  prompt_default: "Q:"
  prompt_search: "S:"
  prompt_cmdlet: "C:"
  keymap: "quickmode_keymap"



# old keymap
# This keymap is tested with macbook with external keyboard..
# Note: Keymap should point to a file instead..
temptemp: {
  # test
  #KeyCode_Shift + KeyCode_UpArrow : NavigateEnd,
  #KeyCode_Ctrl + KeyCode_Shift + KeyCode_UpArrow : NavigateHome,
  # properly mapped
  KeyCode_UpArrow : NavigateLineUp,
  KeyCode_DownArrow : NavigateLineDown,

  # Test - map to same action - but NavigateLineDown will check if this is pressed and invoke selection..
  KeyCode_Shift + KeyCode_DownArrow : NavigateLineDown,
  KeyCode_Shift + KeyCode_UpArrow : NavigateLineUp,

  # Should be able to mark a modifier as 'optional' for an action
  # like: KeyCode_DownArray + @KeyCode_Shift : NavigateDown
  # or:   @KeyCode_Shift + KeyCode_DownArray : NavigateDown
  #
  # This would then insert two actions in the table one with 'Shift' and one without..
  # Or Perhaps lik this:
  #
  # @SelectionModifier + KeyCode_DownArray : NavigateDown
  #
  # Change this to:
  # Action = Key combo
  # Will allow for other stuff like: var <variable> : some key code stuff
  # and then reuse/substitue later will be easier and more 'logical'
  # It also reads like a proper expression...
  #

  KeyCode_LeftArrow : NavigateLineStepLeft,
  KeyCode_RightArrow : NavigateLineStepRight,
  KeyCode_PageUp : NavigatePageUp,
  KeyCode_PageDown : NavigatePageDown,
  KeyCode_Return : CommitLine,
  KeyCode_Command + KeyCode_Home : GotoFirstLine,
  KeyCode_Command + KeyCode_End : GotoLastLine,
  KeyCode_Command + KeyCode_PageUp : GotoTopLine,
  KeyCode_Command + KeyCode_PageDown : GotoBottomLine,
  # doesnt work on MacBookPro laptop keyboard (ALT+Left/RightArrow return 'b'/'f' - modifier is correct!)
  KeyCode_LeftCmd + KeyCode_LeftArrow : NavigateLineWordLeft,
  KeyCode_LeftCmd + KeyCode_RightArrow : NavigateLineWordRight,
  KeyCode_Escape : CycleActiveView,
  KeyCode_F3 : CycleActiveEditor,

  KeyCode_Command + 'c' : CopyToClipboard,
  KeyCode_Command + 'v' : PasteFromClipboard,

}

#
# This defines the terminal to use in the command-view
#
terminal:
  shell: /bin/zsh
  init: -is
  # This is a set of shell commands run after starting the shell..
  # Consider merging with the generic main bootstrap script..
  bootstrap:
    - SET XYZ=4
    - export path=%path%

languages:
  default:
    indent: 4
    tabsize: 4
    insert_spaces: yes
  cpp:
    insert_closing_brace: yes
    auto_indent: yes
    continue_comment: yes
