function main(args) {
    Console.WriteLine("                                                                                ");
    Console.WriteLine("                            @@@@@                                               ");
    Console.WriteLine("                          %*,*///(%                                             ");
    Console.WriteLine("                       &(,,/(%   &(,..*#@                                       ");
    Console.WriteLine("                     %*,*/#&&(,,//*,/%                                          ");
    Console.WriteLine("                  &(,*/(% %*,*///(%                                             ");
    Console.WriteLine("                #*,*/#&&(,..,*/#&                                               ");
    Console.WriteLine("             &(,..,*/#&&(,,/(%                                                  ");
    Console.WriteLine("           #**#@@@&(,...../&                                                    ");
    Console.WriteLine("         #/#&@#/*,......../&                                                    ");
    Console.WriteLine("      %(/*.(&@@@#*,*////*,,,*#                                 @@@@@@@@         ");
    Console.WriteLine("   &#/*,...*//*.,/(%   &(,..,*/#&                            %/...,*///#&       ");
    Console.WriteLine("   &(........,*/#&        &#/*,..*#                        %(*,,*/*,,*///(%     ");
    Console.WriteLine(" %(/*...*#@#*,*/#&          &(,..,*///(%@          &#///*,...,*/*,,*/*,,*//(#&  ");
    Console.WriteLine(" #*..........,*/#&           %(*,..........,*////*,............,*/*,,*//////#&  ");
    Console.WriteLine(" %(/*.*//*.*////#&             %*.................................,*/*,,*///#&  ");
    Console.WriteLine("   &#/*,,*/*,,*///(%           &#///*,.........................,*/*,,*//////#&  ");
    Console.WriteLine("      %(///#&                     %(*,.../%&(,........../% %(*,...,*/*,,*///#&  ");
    Console.WriteLine("                                  %(///*,..*# &#/*,,*//////*,,,,,...,*///(%     ");
    Console.WriteLine("                                    &#/*,,,*# %/,*/*,,# %/........,*///#&       ");
    Console.WriteLine("                                    &#/*,*//*,/% (,,*///*,.,,,,,*///(%          ");
    Console.WriteLine("                                      &(,..,*/*,,# &#(% %/......../%            ");
    Console.WriteLine("                                      &(,,*///#&           (,..,*/#&            ");
    Console.WriteLine("                                     &%/,..*#                %/.../%            ");
    Console.WriteLine("                                      &(,,*(%              (,..,*///(%          ");
    Console.WriteLine("                                    %*.*/*,,*/#&        %/...,*/*,,*///#&       ");
    Console.WriteLine("                                    &#////////#&        %*.,/*,,*//////#&       ");
    Console.WriteLine("                                                                                ");
    Console.WriteLine("    GoatEdit v0.1.0 - by Gnilk - a simple small editor                          ");
    Console.WriteLine("    (c) 2023 Gnilk, see: https://github.com/gnilk/editor                        ");
}